### ISSUE TITLE
Tool doesn't get updating accordingly after toggling annotation

### ISSUE THREAD

**Issue by michael** [substance/archivist-composer#12]
Now selections are preserved after toggling / untoggling an annotation (e.g. bold). However the tool only listens to selection changes to verify it's active state. 

When reapplying of the prev. selection after transaction save, no selection:changed event get fired. 

``` js
tx.save({ selection: Selection.create(path, range[0], range[1]) });
```

Maybe it should fire? Or we need another way of triggering the tools update.

**Comment by obuchtala** [comment]
It should fire... but from within the surface... there is a onDocumentChange handler which should do that.
Will fix later.
