### ISSUE TITLE
Proper messaging when there are errors with saving

### ISSUE THREAD

**Issue by michael** [substance/archivist-composer#15]
Maybe bring back status bar for an error message display... but also thought that displaying a red save icon and some text message near this place would be good.

**Comment by obuchtala** [comment]
Maybe flash messages as used in TAHI?

**Comment by obuchtala** [comment]
(They are positioned absolutly on screen, more like an overlay... and you close each msg).

**Comment by michael** [comment]
you have a screenshot?

**Comment by obuchtala** [comment]
![image](https://cloud.githubusercontent.com/assets/284099/7043307/0b27d90a-dde9-11e4-9261-c29d6cd04556.png)

**Comment by obuchtala** [comment]
they are stacked

**Comment by michael** [comment]
maybe i use one of those growl-like notification libraries for now. Need to check. would like to reach a more minimal presentation eventually. like status bar but with ability to look back when there are overlapping errors. also would like to communicate successes. Like "saved successfully"

**Comment by michael** [comment]
Done.
