### ISSUE TITLE
Mongo Problem: Incrementing of doc version not working properly anymore

### ISSUE THREAD

**Issue by michael** [substance/archivist-composer#16]
while `__v` property gets incremented in database, the change doesn't get reflected in the doc that findByIdAndUpdate returns. 

https://github.com/substance/archivist/blob/next/models/document.js#L192

For example when you save a doc with version 12, `documentVersion: document.__v` will evaluate to 12 after the update instead of 13. This leads to errors of subsequent saves.

I suspect something has changed in mongoose.. so results of findByIdAndUpdate don't have the latest updates.

@Integral can you check that?

It's needed so i can successfully complete and test autosave.

**Comment by Integral** [comment]
fixed
