### ISSUE TITLE
Please verify display of entity cards

### ISSUE THREAD

**Issue by michael** [substance/archivist-composer#18]
I just did a very basic implementation. And i don't know how those items should be presented best. Daniel, maybe you make an iteration here.

The relevant files are here:

https://github.com/substance/archivist-composer/tree/react/src/writer_modules/entities/entity_types

Also you probably want to adjust the styles:

https://github.com/substance/archivist-composer/blob/react/styles/composer.css#L530

**Comment by Integral** [comment]
Did something. Probably will do more later... In the same time i'm wonder where i could fix display of cards which are presented during search?

**Comment by michael** [comment]
that's a generic view atm defined inline.

https://github.com/substance/archivist-composer/blob/react/src/writer_modules/entities/tag_entity_panel.js#L14

We could maybe delegate to the custom implementations you made. However my thought was that we could display less information (e.g. only the name) so it uses less space and is easier to browse when you have to select an entity.

**Comment by Integral** [comment]
Of course, it just have some typos.

**Comment by Integral** [comment]
@michael, have we got some possibilities to reuse entity without searching it again? If not, I believe we need to print description of persons. That's because of during interview you can meet few times one person which name is unknown...

**Comment by michael** [comment]
I don't understand...

You mean when you create an entity reference, that you can choose from already tagged entities first?

Regarding printing the description in the search dialog: you could make a fallback... if name is present use that.. if not.. use description.

**Comment by Integral** [comment]
Let me give you some example!
Imagine that interviewee talks about his brother few times in deferent fragments of interview. But he didn't mention his name! He called him, say, "Rabbit". In this case we will create person which name is Rabbit and in description we'll write "brother of Ivanov Ivan who help him to escape prison camp". And in another interview another interviewee will name his daughter "Rabbit". So we have two "Rabbits" and we can't understand without description which one we actually need.

**Comment by Integral** [comment]
But please don't do anything, i'm just explaining why we need description for persons :) will do it myself

**Comment by Integral** [comment]
@michael I think i did it without touching card size: 9b8aa681e0ea5d09868d593acc89ab3de8bca7c9

**Comment by michael** [comment]
Nice! For info: I'm working on a custom tree implementation in react, so we can have a nicer subject tagging experience.

Reason i'm doing this is that we have some glitches with undo etc and data is lost because of jstree flakyness.

**Comment by Integral** [comment]
OMG, we did it one time already with backbone... Didn't you afraid to entering this time losing spin? :)

**Comment by michael** [comment]
don't worry... THIS TIME it will work ;-)

**Comment by michael** [comment]
looking good.
