### ISSUE TITLE
Basic tree implementation in place

### ISSUE THREAD

**Issue by michael** [substance/archivist-composer#19]
just changes are not stored yet. please have a look if satisfied for a first version daniel. 

will need a bit of tweaking and styling. but now this renders fast without the delays and we can connect the thing to undo/redo functionality of the composer.

**Comment by michael** [comment]
i'm making short break and grab some fresh air

**Comment by Integral** [comment]
i get Uncaught TypeError: Cannot read property 'getDOMNode' of undefined

**Comment by michael** [comment]
Everything updated? Need to check a bit later...

**Comment by Integral** [comment]
i did substance --update

**Comment by michael** [comment]
Oh sorry, please use archivist-composer as a stand-alone until we completed the multi-annotation implementation.

document data structure for subject_references changed a bit, that's why those docs break.

**Comment by Integral** [comment]
it says to me that Uncaught TypeError: Cannot read property 'length' of undefined
and points me at 36 line of http://127.0.0.1:4001/lens/node_modules/substance-writer/src/writer.js

**Comment by michael** [comment]
you don’t have all updates i'm pretty sure. mhh.. let us finish this iteration.. everything pretty much work in progress anyway.

The new tree widget looks like this:

![image](https://cloud.githubusercontent.com/assets/2931/7071741/b0b91d4e-dee7-11e4-9a65-e4a9e037578d.png)

I'm just thinking how we can highlight active items better.

**Comment by Integral** [comment]
Looks good!

**Comment by michael** [comment]
Better like this?

![image](https://cloud.githubusercontent.com/assets/2931/7072300/77debcb4-deeb-11e4-8c5f-b3a6ffc6c445.png)

**Comment by Integral** [comment]
Yes!
