### ISSUE TITLE
Formeditor should not require data-id property on root element

### ISSUE THREAD

**Issue by michael** [substance/archivist-composer#24]
Currently I get an error when switching to the metadata panel. Can this be a rule only for fullfledgededitors but not formeditors?

**Comment by obuchtala** [comment]
We need to consolidate a bit. For now it is that way.

**Comment by obuchtala** [comment]
BTW, need to find a better name probably, as Container is not ContainerNode.
Container is used to describe a surface's structure, which is extracted from the DOM (currently).
Probably we can get rid of that id for form-editors in future.
Plz, give me a better name for 'Container'.

**Comment by obuchtala** [comment]
Thing is that ContainerAnnotations are bound to that structure... so Container is maybe the right name, even if you do not have an underlying ContainerNode. Don't know....

**Comment by obuchtala** [comment]
Added a note as refactoring plan substance/substance@f20ea5a7c6126abdd8f9c51591ff6bf08b363857.

Let's start this work when the main features are completed.

**Comment by obuchtala** [comment]
Done.
