### ISSUE TITLE
Error during breaking when selection is not collapsed

### ISSUE THREAD

**Issue by michael** [substance/archivist-composer#27]
Reproduce:
- make selection within one paragraph (not collapsed)
- hit enter.

**Comment by obuchtala** [comment]
Our ContainerComponent setSelection is causing troubles :(

**Comment by michael** [comment]
ar.. no hack without a price.. :/

**Comment by obuchtala** [comment]
Doing the hack in a timeout seems to work.

**Comment by michael** [comment]
Confirmed
