### ISSUE TITLE
Breaking of entity-refs goes a bit funky

### ISSUE THREAD

**Issue by michael** [substance/archivist-composer#29]
![entity-ref-breaking](https://cloud.githubusercontent.com/assets/2931/7108142/d0623d82-e17c-11e4-9833-cdf5aea8edb0.gif)

**Comment by michael** [comment]
notice that entity record on the right does not disappear... this is because there are some zombie copies of the original annotation remain after split/join/split/join combo...

**Comment by obuchtala** [comment]
Particulary the second time is strange... where the first one gets deleted.
It is obvious that you get two separated ones after merging back... as there is no magic for merging annotations.

**Comment by michael** [comment]
yeah i guess that's fine... i wouldn't be extremely surprised if i get two annotations after split and that they remain after join... but somehow there's more strange things happening.

for entity refs in particular.. maybe it would make sense to make them unbreakable.

**Comment by obuchtala** [comment]
Seems that the first one gets only detached the second time, not deleted.
Everything else behaves as it should.

**Comment by obuchtala** [comment]
See also the same error, when cursor at the end of reference, and then break.

**Comment by obuchtala** [comment]
Fixed.
