### ISSUE TITLE
When trying to type "{12:44" characters are eaten

### ISSUE THREAD

**Issue by michael** [substance/archivist-composer#36]
is there a special treatment for the "{" character..?

**Comment by obuchtala** [comment]
Not eaten, but probably not detected correctly. So they get lost by the rerender.

**Comment by michael** [comment]
It has something to do with the pressing the alt-modifier key to reach some characters. When you enter an alt-modified char then the next char doesn't get detected properly.

**Comment by michael** [comment]
Fiiiiixed.
