### ISSUE TITLE
Pasting few paras from webpage producing errors

### ISSUE THREAD

**Issue by Integral** [substance/archivist-composer#47]
If you pasting one para it usually blocks the content which is now very good (maybe we could define default behaviour like clean all html?)

But when you copy few paras and pasting them, it'll return `TypeError: Cannot read property 'getComponents' of undefined {stack: (...), message: "Cannot read property 'getComponents' of undefined"}`

Steps to reproduce:
- go to [http://substance.io/about/](http://substance.io/about/)
- navigate to Oliver Buchtala's section and copy few paras like bio and "Find him on Github" 
- paste it to composer

**Comment by Integral** [comment]
Or you can just copy few paras from my bug report here :)

**Comment by obuchtala** [comment]
Fixed.
