### ISSUE TITLE
When implicitly deleting a subject reference (surrending content gets removed) there are some zombies left

### ISSUE THREAD

**Issue by michael** [substance/archivist-composer#53]
in fact there's start and end anchor and also a zero-length span in the markup. desired behavior would be that everything goes away.

**Comment by michael** [comment]
this happens when in the case of a container selection.

before: 

![image](https://cloud.githubusercontent.com/assets/2931/7263903/f5432a7a-e885-11e4-8d32-1ecdb7ebaf80.png)

after:

![image](https://cloud.githubusercontent.com/assets/2931/7263906/fd71e538-e885-11e4-8af9-b2b5dee987c0.png)

**Comment by michael** [comment]
this does not happen for remark annotations. so i guess after we refactor the tag_subject_tool to use the annotation_tool mixin it will be fixed.

**Comment by michael** [comment]
mhh but actually it can not be related to the deletion (that's not related to the tool stuff) - strange.

**Comment by obuchtala** [comment]
It is a new edge case: the annotation anchors are on two different nodes still, so it is not collapsed and will not be deleted. Any idea how we want to deal with it?

**Comment by obuchtala** [comment]
A wait... that is only before merging...
ATM ContainerAnnotations get deleted when the collapsed during a property delete.

**Comment by obuchtala** [comment]
Fixed.
