### ISSUE TITLE
Subjects got removed without proper reason

### ISSUE THREAD

**Issue by Integral** [substance/archivist-composer#54]
![](http://s11.postimg.org/rgqzpyf6b/Screen_Shot_2015_04_22_at_00_27_01.png)

Steps to reproduce:
- select fragment as shown in image (end of first subject, whole next subject, and next para)
- hit remove

it'll remove all two subjects while first subject was not selected entirely

**Comment by obuchtala** [comment]
The problem is, that the node gets deleted where the end anchor is located.
Need some logic shich moves the anchor to a new proper location.

**Comment by obuchtala** [comment]
Done.
