### ISSUE TITLE
Implement Annotation.getText()

### ISSUE THREAD

**Issue by michael** [substance/archivist-composer#59]
This is needed for the completion of the remarks panel. Plan is this:
- in the remark component listen to updates to that anno
- in the render method we just use remark.getText() for the title and provide a maximum length

@oliver---- Do you see any problems with Annotation.getText(), is it hard to do it for instance for containerannotations?

We could also make this low priority. Would be nice demo of how reactive everything is though ;)

**Comment by obuchtala** [comment]
var Substance = require('./node_modules/substance/index.js')
var sel = Substance.Document.Selection.create(doc.get('content'), ['text_1', 'content'], 10, ['text_2', 'content'], 59);
doc.getTextForSelection(sel)
"m dolor sit amet, consectetur adipiscing elit. Phasellus quis scelerisque ligula. Proin tristique ligula id magna finibus rhoncus. Quisque dictum viverra sapien, vel elementum metus condimentum nec. Donec ac tellus nunc. Nullam fermentum pharetra justo, accumsan tristique quam tempus a. Quisque vitae luctus velit. Praesent lacinia enim ex, sed pulvinar neque dictum ultricies. Sed est metus, bibendum sed suscipit ut, cursus ut mi. Pellentesque sagittis mi nisi, eu blandit metus congue id. Pellentesque eget magna porta, rutrum odio et, commodo lacus. Sed vitae vehicula ante. Quisque suscipit iaculis est, vitae aliquet lacus dictum ut. Nulla enim dolor, pulvinar at odio vitae, sollicitudin eleifend ex. Maecenas eget ligula eget sem efficitur consectetur nec vel sem. In massa mauris, consequat vitae enim eget, vehicula aliquet turpis.Proin in luctus sapien, ultrices commodo augue. Phasellus u"
