### ISSUE TITLE
Hitting enter inside a property annotation when wrapped with a container annotations blows up things

### ISSUE THREAD

**Issue by michael** [substance/archivist-composer#61]
before:
![image](https://cloud.githubusercontent.com/assets/2931/7287047/6a0e6e84-e951-11e4-9b0e-8a768381302b.png)

after:

![image](https://cloud.githubusercontent.com/assets/2931/7287057/90f8d174-e951-11e4-95d2-5e65c786421e.png)

**Comment by obuchtala** [comment]
Fixed.
