### ISSUE TITLE
When clicking inside a remark text the cursor ends up in the first position

### ISSUE THREAD

**Issue by michael** [substance/archivist-composer#62]
Reproduce:
- click on remarks tab
- click inside of the editable content area

Remark gets highlighted but cursor gets set to first pos. i tried to adjust this after the state change but failed with it.

What would be the correct way to do that?

https://github.com/substance/archivist-composer/blob/master/src/writer_modules/remarks/remarks_panel.js#L42

**Comment by obuchtala** [comment]
It's just surface.rerenderSelection()
